### model
model_name_or_path: /home/qianwenhao/LLM/Qwen3-1.7B
# trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_alpha: 32
lora_target: q_proj,v_proj
deepspeed: config/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]
report_to: none

### dataset
dataset: text2sql
template: qwen3
cutoff_len: 1024
max_samples: 126641
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen3-1.7B/lora/sft
logging_steps: 25
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 2.0e-5
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr: 1.0e-06
num_train_epochs: 3.0
warmup_ratio: 0.01
weight_decay: 0.01
optim: adamw_8bit # added
bf16: true
ddp_timeout: 180000000
seed: 42 # added

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
