### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: /home/qianwenhao/LLM/Qwen3-1.7B
adapter_name_or_path: saves/qwen3-1.7B/lora/sft
template: qwen3
trust_remote_code: true

### export
export_dir: saves/qwen3-1.7B/lora/sft/merged
export_size: 5
export_device: auto  # choices: [cpu, auto]
export_legacy_format: false